name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Install Varnish Enterprise repository
        run: |
          curl -s https://packagecloud.io/install/repositories/varnishplus/60-enterprise/script.deb.sh | sudo bash

      - name: Install Varnish Enterprise packages
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_SUSPEND=non-empty-value apt-get install -y \
            varnish-plus \
            varnish-plus-ha \
            varnish-plus-vmods-extra

      - name: Check VCL syntax
        working-directory: vcl
        run: |
          check_vcl_syntax() {
            local output

            output=$(mktemp)
            if ! varnishd \
                -C \
                -f "$PWD/main.vcl" \
                -p "vcl_path=$PWD:/usr/share/varnish-plus/vcl" \
                >"$output" 2>&1; then
              cat "$output"
              exit 1
            fi
          }

          # Check syntax including 'akamai.vcl' and one replication strategy at
          # a time.
          for REPLICATION in disabled vha cluster; do
            sed -i \
              -e 's/^# \(include "akamai\.vcl";\)/\1/' \
              -e 's/^\(include "replication-.*\.vcl"\);/# \1;/' \
              -e "s/^# \(include \"replication-$REPLICATION\.vcl\";\)/\1/" \
              main.vcl
            check_vcl_syntax
          done
          git checkout -- main.vcl

          # Check syntax including one environment at a time.
          for ENVIRONMENT in local pro; do
            sed -i "s/^include \"environment-.*\.vcl\";/include \"environment-$ENVIRONMENT.vcl\";/" environment.vcl
            check_vcl_syntax
          done
          git checkout -- environment.vcl

      - name: Run tests
        working-directory: tests
        run: ./run-tests.sh
