name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - run: docker build --tag vclski-dev .

      - run: |
          docker run \
            --rm \
            --entrypoint bash \
            --volume ${{ github.workspace }}:/workspace \
            --workdir /workspace \
            vclski-dev \
            -c './tests/run-tests.sh'
